jenkins:
  systemMessage: |
    Welcome to our build server.

    This Jenkins is 100% configured and managed 'as code'.
    Config is now mostly handled by the 'Jenkins Configuration as Code' (JCasC) plugin.
    JCasC config can be found in the /usr/share/jenkins/ref/casc_configs folder.

    Some settings are still injected from /usr/share/jenkins/ref/init.groovy.d/ scripts,
    but these settings will be ported over to JCasC as support becomes available.
    See https://github.com/nxtlytics/jenkins-controller for more
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: false
  mode: EXCLUSIVE
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  quietPeriod: 5
  scmCheckoutRetryCount: 0
  slaveAgentPort: 50000
  views:
  - all:
      name: "all"
  slaveAgentPort: 50000
unclassified:
  themeManager:
    disableUserThemes: true
    theme: "darkSystem" # use 'dark' for forcing the dark theme regardless of OS settings
